### ISSUE TITLE
Feature: 希望能够支持ARM64架构系统

### ISSUE THREAD

**Issue by hanasa2023** [A-kirami/matcha#127]
### 确认事项

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确认功能并未实现。
- [X] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的需求。

### 你希望能解决什么样的问题？

希望能够支持ARM64架构系统

### 你想要的解决方案

能够在ARM64架构系统上运行

### 参与贡献

- [ ] 我有足够的时间和能力，愿意为此提交 PR 来实现功能。

**Comment by A-kirami** [comment]
已支持 arm64，可在 actions 的附件中下载
