### ISSUE TITLE
BUG: 窗口的亚克力效果会导致调整窗口大小或拖动窗口时出现性能问题

### ISSUE THREAD

**Issue by Well2333** [A-kirami/matcha#170]
### 确认事项

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确认功能并未实现。
- [X] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的需求。

### 你希望能解决什么样的问题？

窗口平滑移动可能看起来很酷炫，但是对于移动窗口来说，此项功能完全华而不实，甚至会影响移动窗口的精度，因此市面上几乎没有任何应用采用了此功能

### 你想要的解决方案

移除或添加开关以禁用此功能

### 参与贡献

- [ ] 我有足够的时间和能力，愿意为此提交 PR 来实现功能。

**Comment by A-kirami** [comment]
有动图或者视频补充吗？

**Comment by Reversedeer** [comment]
刚更新到最新版，效果如视频所示，窗口拖动很难受...
https://github.com/user-attachments/assets/46dd39a9-eb3e-4a96-b743-bd8b9cf021bb
