### ISSUE TITLE
Feature: 添加日志消息的位置选项

### ISSUE THREAD

**Issue by shoucandanghehe** [A-kirami/matcha#179]
### 确认事项

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确认功能并未实现。
- [X] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的需求。

### 你希望能解决什么样的问题？

在重启bot后，弹出的断连/重连日志消息会遮挡发送按钮
或许可以把日志丢中间悬浮或者直接关掉

### 你想要的解决方案

添加日志消息的位置选项

### 参与贡献

- [ ] 我有足够的时间和能力，愿意为此提交 PR 来实现功能。

**Comment by A-kirami** [comment]
目前这种样式的重连提示不适合放置在中间
并且提示有持续时间，也可以手动关闭
如果重连次数过多，提示太多，可以在设置中将“显示连接错误”关闭
