### ISSUE TITLE
[Feature]: 提供Win下免安装release

### ISSUE THREAD

**Issue by kexue-z** [A-kirami/matcha#3]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确认功能并未实现。
- [X] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的需求。
- [X] 我有足够的时间和能力，愿意为此提交 PR 来实现功能。

### 您希望能解决什么样的问题？

使用msi安装时，需要请求管理员权限。然而我所在公司的电脑没有管理员权限，因此无法使用。

### 您想要的解决方案

提供exe免安装版本，或者压缩包。可以下载后双击直接运行的。

**Comment by A-kirami** [comment]
由于此应用程序使用 Tauri 构建，它依赖于  Webview2，需要由安装程序进行相关检查和安装，所以免安装的二进制文件并不适用于全部 Windows 平台。

如果你需要便携式的二进制文件，你可以尝试以下步骤：

1. 确保你使用的系统是Windows 10（2018年4月发布或更高版本）或 Windows 11，因为在这些版本中 Webview2 运行时作为操作系统的一部分分发，或者你可以尝试自行安装 Webview2。
2. 安装 node（18）、pnpm（7）、rust。
3. 克隆此存储库到本地。
4. 在项目目录下运行以下命令安装依赖：

       pnpm i

5. 运行以下命令以构建二进制文件：

       pnpm tauri build

6. 构建完成后，你可以在 `/src-tauri/target/release` 目录下找到 `matcha.exe`
