### ISSUE TITLE
[Feature]: UI问题有点多，想要重新做一下

### ISSUE THREAD

**Issue by roiiiu** [A-kirami/matcha#54]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确认功能并未实现。
- [X] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的需求。
- [X] 我有足够的时间和能力，愿意为此提交 PR 来实现功能。

### 您希望能解决什么样的问题？

响应式，还有tauri的窗口设置都有些问题。
<img width="320" alt="image" src="https://user-images.githubusercontent.com/11494827/236645104-d7f034db-64b3-48ba-8de4-a733ba8526a5.png">

### 您想要的解决方案

我可以重写一部分vue的内容，或许可以详细讨论下。

**Comment by A-kirami** [comment]
你觉得有哪些地方需要重构或者修改？[响应式布局的改进](https://github.com/users/A-kirami/projects/8?query=is%3Aopen+sort%3Aupdated-desc&pane=issue&itemId=23614930)虽然在计划中的优先级不高，不过如果你有兴趣重构它，我也十分欢迎。

**Comment by roiiiu** [comment]
> 你觉得有哪些地方需要重构或者修改？[响应式布局的改进](https://github.com/users/A-kirami/projects/8?query=is%3Aopen+sort%3Aupdated-desc&pane=issue&itemId=23614930)虽然在计划中的优先级不高，不过如果你有兴趣重构它，我也十分欢迎。

ChatContact是想要做成什么样的响应式效果呢，我觉得它不该被缩放，如果你同意我会提个pr，优化一些效果。

**Comment by roiiiu** [comment]
还有，我觉得不该把路由全部KeepAlive，这样会严重影响性能。

**Comment by A-kirami** [comment]
> > 你觉得有哪些地方需要重构或者修改？[响应式布局的改进](https://github.com/users/A-kirami/projects/8?query=is%3Aopen+sort%3Aupdated-desc&pane=issue&itemId=23614930)虽然在计划中的优先级不高，不过如果你有兴趣重构它，我也十分欢迎。
> 
> ChatContact是想要做成什么样的响应式效果呢，我觉得它不该被缩放，如果你同意我会提个pr，优化一些效果。

文字部分自适应宽度，当文字宽度过小时，仅保留头像，新消息数以徽标形式展示在头像上。

效果大致如下图

![image](https://user-images.githubusercontent.com/66513481/236668416-27007cc1-063c-4184-b0f3-6bdaf16b24d3.png)

**Comment by A-kirami** [comment]
> 还有，我觉得不该把路由全部KeepAlive，这样会严重影响性能。

你是指每个会话吗？还是侧边栏

**Comment by roiiiu** [comment]
> > > 你觉得有哪些地方需要重构或者修改？[响应式布局的改进](https://github.com/users/A-kirami/projects/8?query=is%3Aopen+sort%3Aupdated-desc&pane=issue&itemId=23614930)虽然在计划中的优先级不高，不过如果你有兴趣重构它，我也十分欢迎。
> > 
> > 
> > ChatContact是想要做成什么样的响应式效果呢，我觉得它不该被缩放，如果你同意我会提个pr，优化一些效果。
> 
> 文字部分自适应宽度，当文字宽度过小时，仅保留头像，新消息数以徽标形式展示在头像上。
> 
> 效果大致如下图
> 
> ![image](https://user-images.githubusercontent.com/66513481/236668416-27007cc1-063c-4184-b0f3-6bdaf16b24d3.png)

嗯🤔了解，类似discord那种

**Comment by A-kirami** [comment]
> > > > 你觉得有哪些地方需要重构或者修改？[响应式布局的改进](https://github.com/users/A-kirami/projects/8?query=is%3Aopen+sort%3Aupdated-desc&pane=issue&itemId=23614930)虽然在计划中的优先级不高，不过如果你有兴趣重构它，我也十分欢迎。
> > > 
> > > 
> > > ChatContact是想要做成什么样的响应式效果呢，我觉得它不该被缩放，如果你同意我会提个pr，优化一些效果。
> > 
> > 
> > 文字部分自适应宽度，当文字宽度过小时，仅保留头像，新消息数以徽标形式展示在头像上。
> > 效果大致如下图
> > ![image](https://user-images.githubusercontent.com/66513481/236668416-27007cc1-063c-4184-b0f3-6bdaf16b24d3.png)
> 
> 嗯🤔了解，类似discord那种

我还没有使用过 discord，不过如果类似的话，你可以参考它，或者自己进行一些改进？我感觉现在的设计并不是最好的

**Comment by roiiiu** [comment]
https://user-images.githubusercontent.com/11494827/236680804-626ee2cb-44ac-4b6c-b1b7-13f70a323530.mp4


做了个小demo，我觉得保留原生窗口title比较好，在不同平台割裂感也不是很强。

**Comment by A-kirami** [comment]
> 2023-05-07.21-33-56.mp4 
> 做了个小demo，我觉得保留原生窗口title比较好，在不同平台割裂感也不是很强。

大小改变的时候，Contact 的文字部分没有变化，感觉有些怪。

至于原生窗口标题，win 这边的标题栏不算太好看……

**Comment by roiiiu** [comment]
> > 2023-05-07.21-33-56.mp4
> > 做了个小demo，我觉得保留原生窗口title比较好，在不同平台割裂感也不是很强。
> 
> 大小改变的时候，Contact 的文字部分没有变化，感觉有些怪。
> 
> 至于原生窗口标题，win 这边的标题栏不算太好看……

是吗，我反而觉得变化才会怪，看来看法有些差异😆

**Comment by A-kirami** [comment]
> > > 2023-05-07.21-33-56.mp4
> > > 做了个小demo，我觉得保留原生窗口title比较好，在不同平台割裂感也不是很强。
> > 
> > 
> > 大小改变的时候，Contact 的文字部分没有变化，感觉有些怪。
> > 至于原生窗口标题，win 这边的标题栏不算太好看……
> 
> 是吗，我反而觉得变化才会怪，看来看法有些差异😆

可以给聊天区域一个最小宽度，到达之后开始缩减联系人区域的宽度，这样观感可能会好一些

**Comment by ChrisKimZHT** [comment]
还有聊天列表不会自动滚动到底部，每次 bot 回复都得手动滚轮滚下去，这个挺影响效率的。

**Comment by A-kirami** [comment]
> 还有聊天列表不会自动滚动到底部，每次 bot 回复都得手动滚轮滚下去，这个挺影响效率的。

自动滚动是有的

**Comment by kexue-z** [comment]
你看看这是什么.jpg
![image](https://github.com/A-kirami/matcha/assets/71873002/b718e33a-3186-447d-be20-0e7d8e39f814)
