### ISSUE TITLE
[Feature]: 用户列表、聊天列表的排序、删除功能

### ISSUE THREAD

**Issue by kexue-z** [A-kirami/matcha#96]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确认功能并未实现。
- [X] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的需求。
- [ ] 我有足够的时间和能力，愿意为此提交 PR 来实现功能。

### 您希望能解决什么样的问题？

聊天列表里面，创建了群聊就不能删除和编辑了；

用户列表里面，也不能删除、编辑用户的信息

### 您想要的解决方案

聊天列表里面添加拖动排序，并且添加右键菜单，让他可以删除或进入编辑

用户列表里面，添加拖动排序，并且添加右键菜单，让他可以删除或进入编辑

而且，添加用户应该放在用户列表里面才对吧。

### 还有什么要补充的吗？

略略略

**Comment by A-kirami** [comment]
聊天列表和用户列表不会有手动排序，聊天列表预期是按照最近聊天时间来排序，用户列表预期是按最近使用的身份排序，如果你对自动排序有改进建议可以提供。

用户列表目前实际上是个赶工的产物，之后会重构。

至于添加用户放在用户列表里，这点没有确定。

因为一般聊天应用是把添加用户和添加群组放一块的吧，感觉分开放是不是不太统一。

**Comment by kexue-z** [comment]
因为你这个默认顶置了对Bot的聊天，所有我想着整个排序挺好的）

那删除和编辑那些捏

**Comment by A-kirami** [comment]
> 因为你这个默认顶置了对Bot的聊天，所有我想着整个排序挺好的）
> 
> 那删除和编辑那些捏

这个需要重构 UI 之后才能实现，目前创建用户和群的 UI 是赶工产物，等重构之后就能支持编辑了

**Comment by kexue-z** [comment]
速速重构（
