### ISSUE TITLE
[Feature]: 发送消息时或收到新消息时，将当前聊天页面滑动到最下方

### ISSUE THREAD

**Issue by Decrabbityyy** [A-kirami/matcha#98]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确认功能并未实现。
- [X] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的需求。
- [ ] 我有足够的时间和能力，愿意为此提交 PR 来实现功能。

### 您希望能解决什么样的问题？

每次发完消息等bot回复完需要手动滑动滚轮，希望可以直接显示bot回复的消息

### 您想要的解决方案

发送消息时或收到新消息时，将当前聊天页面滑动到最下方

### 您考虑过的替代方案

添加一个到达最下方的按钮

**Comment by A-kirami** [comment]
![scroll](https://github.com/A-kirami/matcha/assets/66513481/f7091a94-c078-4ec8-b792-fb8625000c22)

这在第一版就已经实现，如果这在你的电脑上表现不正常，请提供运行应用的系统及版本信息

**Comment by Decrabbityyy** [comment]
![Matcha 2023-06-05 19-46-45.1.gif](https://github.com/A-kirami/matcha/assets/99632363/80c63907-bab3-4fb3-bf19-a876433f719b)

win11 系统版本22621.1702
Matcha版本 v0.2.4

**Comment by A-kirami** [comment]
> ![Matcha 2023-06-05 19-46-45.1.gif](https://github.com/A-kirami/matcha/assets/99632363/80c63907-bab3-4fb3-bf19-a876433f719b)
> ![Matcha 2023-06-05 20-00-47.gif](https://github.com/A-kirami/matcha/assets/99632363/78225e56-091f-4d2e-b0e5-08044265f8f0)
> win11 系统版本22621.1702
> Matcha版本 v0.2.4

是全程没有自动滚动吗？

**Comment by Decrabbityyy** [comment]
> > ![Matcha 2023-06-05 19-46-45.1.gif](https://user-images.githubusercontent.com/99632363/243347847-80c63907-bab3-4fb3-bf19-a876433f719b.gif)
> > ![Matcha 2023-06-05 20-00-47.gif](https://user-images.githubusercontent.com/99632363/243350785-78225e56-091f-4d2e-b0e5-08044265f8f0.gif)
> > win11 系统版本22621.1702
> > Matcha版本 v0.2.4
> 
> 是全程没有自动滚动吗？
前几条消息有自动滚动，当发送消息超过显示区域开始就没有自动滚动了

**Comment by Decrabbityyy** [comment]
前几条消息是有自动滚动的。当聊天窗口的消息超过显示区域时，自动滚动就不工作了
